import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { Pencil, FolderPlus } from 'lucide-react';
import { ResourcePage, Badge } from '../../components/data/resource-page';
import { EntitySelect } from '../../components/data/entity-select';
import { Dialog } from '../../components/ui/dialog';
import { Button } from '../../components/ui/button';
import { api, post } from '../../lib/api';
import { money, number } from '../../lib/utils';
import { useAuth } from '../auth/auth';
export interface CatalogItem {id:string;name:string;sku:string;categoryId:string;category:{name:string};baseUnit?:string;unit?:string;minimumStock:string;salePrice?:string;active:boolean}
const unitOptions=['KG','G','L','ML','UNIT'];
export function Catalog({kind}:{kind:'ingredients'|'products'}) {
 const [editing,setEditing]=useState<CatalogItem|null|undefined>(undefined);const [category,setCategory]=useState(false);const [notice,setNotice]=useState('');const {user}=useAuth(); const writable=['ADMIN','MANAGER','STOCK'].includes(user?.role??'');
 const product=kind==='products';const client=useQueryClient();
 const done=()=>{setEditing(undefined);setCategory(false);setNotice('Registro salvo com sucesso.');void client.invalidateQueries();};
 return <><ResourcePage<CatalogItem> title={product?'Produtos':'Insumos'} description={product?'Produtos da casa, preços e parâmetros da operação.':'Matérias-primas organizadas para cada receita e cada fornada.'} endpoint={'/'+kind} action={writable?{label:product?'Novo produto':'Novo insumo',run:()=>setEditing(null)}:undefined} filters={[{value:'ACTIVE',label:'Ativos'},{value:'INACTIVE',label:'Inativos'}]} extra={<div className="flex justify-between mb-4">{notice&&<p role="status" className="text-sm text-emerald-600">{notice}</p>}{writable&&<Button variant="outline" size="sm" onClick={()=>setCategory(true)}><FolderPlus size={15}/>Nova categoria</Button>}</div>} columns={[{label:'NOME / CÓDIGO',render:r=><div><Link className="font-medium hover:text-primary" to={'/'+kind+'/'+r.id}>{r.name}</Link><p className="text-xs text-muted-foreground mt-1">{r.sku}</p></div>},{label:'CATEGORIA',render:r=>r.category.name},{label:'UNIDADE',render:r=>r.baseUnit??r.unit},{label:product?'PREÇO DE VENDA':'ESTOQUE MÍNIMO',render:r=>product?money(r.salePrice):number(r.minimumStock)+' '+r.baseUnit},{label:'STATUS',render:r=><Badge tone={r.active?'success':'neutral'}>{r.active?'Ativo':'Inativo'}</Badge>},{label:'',render:r=>writable?<Button variant="ghost" size="icon" aria-label={'Editar '+r.name} onClick={()=>setEditing(r)}><Pencil size={15}/></Button>:null}]}/>{editing!==undefined&&<CatalogForm kind={kind} item={editing} onClose={()=>setEditing(undefined)} onDone={done}/ >}{category&&<Dialog title="Nova categoria" onClose={()=>setCategory(false)}><form className="space-y-4" onSubmit={async e=>{e.preventDefault();const data=new FormData(e.currentTarget);try{await post('/categories/'+(product?'product':'ingredient'),{name:data.get('name')});done();}catch(error){setNotice(error instanceof Error?error.message:'Falha ao salvar');}}}><label className="field">Nome<input name="name" minLength={2} maxLength={80} required/></label><Button>Salvar categoria</Button></form></Dialog>}</>;
}
function CatalogForm({kind,item,onClose,onDone}:{kind:'ingredients'|'products';item:CatalogItem|null;onClose:()=>void;onDone:()=>void}) {
 const [error,setError]=useState('');const [categoryId,setCategoryId]=useState(item?.categoryId??'');const product=kind==='products';
 const {register,handleSubmit,formState:{isSubmitting}}=useForm({defaultValues:{name:item?.name??'',sku:item?.sku??'',unit:item?.unit??item?.baseUnit??'KG',minimumStock:Number(item?.minimumStock??0),salePrice:Number(item?.salePrice??0),active:item?.active??true}});
 return <Dialog title={item?'Editar cadastro':product?'Novo produto':'Novo insumo'} onClose={onClose}><form className="space-y-5" onSubmit={handleSubmit(async data=>{try{await api('/'+kind+(item?'/'+item.id:''),{method:item?'PUT':'POST',body:JSON.stringify({name:data.name,sku:data.sku,categoryId,minimumStock:Number(data.minimumStock),active:data.active,...(product?{unit:data.unit,salePrice:Number(data.salePrice)}:{baseUnit:data.unit})})});onDone();}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar');}})}><div className="grid sm:grid-cols-2 gap-4"><label className="field">Nome<input required minLength={2} maxLength={120} {...register('name')}/></label><label className="field">Código SKU<input required minLength={2} maxLength={40} {...register('sku')}/></label></div><EntitySelect label="Categoria" endpoint={'/categories/'+(product?'product':'ingredient')} value={categoryId} onChange={setCategoryId}/><div className="grid sm:grid-cols-3 gap-4"><label className="field">Unidade<select {...register('unit')}>{unitOptions.map(u=><option key={u}>{u}</option>)}</select></label><label className="field">Estoque mínimo<input type="number" min="0" step="0.001" required {...register('minimumStock')}/></label>{product&&<label className="field">Preço de venda (R$)<input type="number" min="0" step="0.01" required {...register('salePrice')}/></label>}</div><label className="flex gap-2 text-sm"><input type="checkbox" {...register('active')}/>Cadastro ativo</label>{error&&<p role="alert" className="text-sm text-red-600">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>Cancelar</Button><Button disabled={isSubmitting||!categoryId}>{isSubmitting?'Salvando…':'Salvar cadastro'}</Button></div></form></Dialog>;
}
