import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { Plus, Trash2, ArrowLeft } from 'lucide-react';
import { api, post } from '../../lib/api';
import { number, date } from '../../lib/utils';
import { ResourcePage, Badge } from '../../components/data/resource-page';
import { EntitySelect } from '../../components/data/entity-select';
import { Button } from '../../components/ui/button';
import { Dialog } from '../../components/ui/dialog';
import { ErrorState, Loading } from '../../components/feedback/states';
import { useAuth } from '../auth/auth';
export interface Recipe {id:string;name:string;active:boolean;productId:string;product:{name:string;unit:string};versions:Version[]}
interface Version {id:string;version:number;yieldQuantity:string;createdAt:string;items:{ingredientId:string;quantity:string;unit:string;ingredient:{name:string}}[]}
export function Recipes() {
 const [create,setCreate]=useState(false);const client=useQueryClient();const {user}=useAuth();const write=['ADMIN','MANAGER','STOCK'].includes(user?.role??'');
 return <><ResourcePage<Recipe> title="Receitas" description="Fichas técnicas versionadas. Cada produção preserva a receita utilizada." endpoint="/recipes" action={write?{label:'Nova receita',run:()=>setCreate(true)}:undefined} filters={[{value:'ACTIVE',label:'Ativas'},{value:'INACTIVE',label:'Inativas'}]} columns={[{label:'RECEITA',render:r=><Link className="font-medium hover:text-primary" to={'/recipes/'+r.id}>{r.name}</Link>},{label:'PRODUTO',render:r=>r.product.name},{label:'VERSÃO ATUAL',render:r=><Badge>v{r.versions[0]?.version}</Badge>},{label:'RENDIMENTO',render:r=>number(r.versions[0]?.yieldQuantity)+' '+r.product.unit},{label:'STATUS',render:r=><Badge tone={r.active?'success':'neutral'}>{r.active?'Ativa':'Inativa'}</Badge>}]}/>{create&&<RecipeForm onClose={()=>setCreate(false)} onDone={()=>{setCreate(false);void client.invalidateQueries();}}/>}</>;
}
export function RecipeDetail() {
 const {id}=useParams();const query=useQuery({queryKey:['recipe',id],queryFn:()=>api<Recipe>('/recipes/'+id)});const [creating,setCreating]=useState(false);const client=useQueryClient();const {user}=useAuth();
 if(query.isPending)return <Loading/>;if(query.isError)return <ErrorState error={query.error}/>;const r=query.data;
 return <><Link to="/recipes" className="inline-flex gap-2 text-sm text-muted-foreground mb-6"><ArrowLeft size={16}/>Receitas</Link><div className="flex justify-between gap-4 flex-wrap"><div><h1 className="page-title">{r.name}</h1><p className="page-description">{r.product.name} · Histórico de versões preservado</p></div>{['ADMIN','MANAGER','STOCK'].includes(user?.role??'')&&<Button onClick={()=>setCreating(true)}><Plus size={16}/>Nova versão</Button>}</div><div className="grid gap-5 mt-8">{r.versions.map(v=><section className="card" key={v.id}><div className="flex justify-between mb-5"><h2 className="font-semibold">Versão {v.version} <span className="text-sm font-normal text-muted-foreground ml-2">{date(v.createdAt)}</span></h2><Badge>Rendimento: {number(v.yieldQuantity)} {r.product.unit}</Badge></div><div className="overflow-x-auto"><table><thead><tr><th>INSUMO</th><th>QUANTIDADE</th></tr></thead><tbody>{v.items.map(i=><tr key={i.ingredientId}><td>{i.ingredient.name}</td><td>{number(i.quantity,6)} {i.unit}</td></tr>)}</tbody></table></div></section>)}</div>{creating&&<RecipeForm recipe={r} onClose={()=>setCreating(false)} onDone={()=>{setCreating(false);void client.invalidateQueries();}}/>}</>;
}
function RecipeForm({recipe,onClose,onDone}:{recipe?:Recipe;onClose:()=>void;onDone:()=>void}) {
 const [productId,setProductId]=useState(recipe?.productId??'');const [name,setName]=useState(recipe?.name??'');const [yieldQuantity,setYield]=useState(Number(recipe?.versions[0]?.yieldQuantity??1));const [items,setItems]=useState(recipe?.versions[0]?.items.map(i=>({ingredientId:i.ingredientId,quantity:Number(i.quantity),unit:i.unit}))??[{ingredientId:'',quantity:1,unit:'KG'}]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 return <Dialog title={recipe?'Nova versão da receita':'Nova receita'} onClose={onClose}><form className="space-y-5" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await post(recipe?'/recipes/'+recipe.id+'/versions':'/recipes',{...(recipe?{}:{name,productId}),yieldQuantity,items});onDone();}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar');}finally{setBusy(false);}}}>{!recipe&&<><label className="field">Nome da receita<input value={name} onChange={e=>setName(e.target.value)} minLength={2} required/></label><EntitySelect label="Produto" endpoint="/products?status=ACTIVE" value={productId} onChange={setProductId}/></>}<label className="field">Rendimento na unidade do produto<input type="number" min=".000001" step=".000001" value={yieldQuantity} onChange={e=>setYield(Number(e.target.value))} required/></label><h3 className="text-sm font-semibold">Ingredientes</h3>{items.map((item,index)=><div className="border rounded-lg p-4 space-y-3" key={index}><EntitySelect label={'Insumo '+(index+1)} endpoint="/ingredients?status=ACTIVE" value={item.ingredientId} onChange={value=>setItems(items.map((i,n)=>n===index?{...i,ingredientId:value}:i))}/><div className="flex gap-3"><input aria-label={'Quantidade '+(index+1)} type="number" min=".000001" step=".000001" value={item.quantity} onChange={e=>setItems(items.map((i,n)=>n===index?{...i,quantity:Number(e.target.value)}:i))} required/><select aria-label={'Unidade '+(index+1)} value={item.unit} onChange={e=>setItems(items.map((i,n)=>n===index?{...i,unit:e.target.value}:i))}>{['KG','G','L','ML','UNIT'].map(u=><option key={u}>{u}</option>)}</select><Button type="button" variant="ghost" size="icon" aria-label="Remover insumo" disabled={items.length===1} onClick={()=>setItems(items.filter((_,n)=>n!==index))}><Trash2 size={16}/></Button></div></div>)}<Button type="button" variant="outline" onClick={()=>setItems([...items,{ingredientId:'',quantity:1,unit:'KG'}])}><Plus size={16}/>Adicionar insumo</Button>{error&&<p role="alert" className="text-red-600 text-sm">{error}</p>}<p className="text-xs text-muted-foreground">Versões anteriores permanecem inalteradas. Uma nova receita torna-se a ficha ativa deste produto.</p><Button disabled={busy||items.some(i=>!i.ingredientId)||!productId} className="w-full">{busy?'Salvando…':'Salvar ficha técnica'}</Button></form></Dialog>;
}
