import { useState } from 'react';
import { Navigate } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { ArrowRight, Wheat, Layers3, ShieldCheck } from 'lucide-react';
import { useAuth } from './auth';
import { Button } from '../../components/ui/button';
const schema = z.object({ email: z.email('Informe um e-mail válido.'), password: z.string().min(1, 'Informe a senha.') });
export function Login() {
 const auth = useAuth(); const [error, setError] = useState('');
 const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<z.infer<typeof schema>>({ resolver: zodResolver(schema) });
 if (auth.user) return <Navigate to="/" replace/>;
 return <div className="min-h-screen grid lg:grid-cols-2"><aside className="hidden lg:flex bg-[#1C1917] text-stone-100 p-16 flex-col justify-between"><div className="flex items-center gap-3 font-bold tracking-[.2em]"><Wheat className="text-[#D49A62]"/>BAKEFLOW</div><div><span className="text-[#D49A62] text-xs uppercase tracking-[.2em]">Do primeiro ingrediente à última fornada</span><h1 className="text-5xl leading-tight font-semibold mt-5 max-w-lg">Mais controle.<br/>Menos desperdício.<br/>Melhores fornadas.</h1><p className="text-stone-400 max-w-md mt-6 leading-relaxed">Estoque, compras e produção conectados para cuidar de cada detalhe da sua padaria.</p><div className="flex gap-8 mt-12 text-sm text-stone-300"><span className="flex gap-2"><Layers3 size={18}/>Rastreabilidade</span><span className="flex gap-2"><ShieldCheck size={18}/>Operação segura</span></div></div><p className="text-sm text-stone-500">Padaria Santa Massa · Ambiente de demonstração</p></aside><main className="flex items-center justify-center p-8"><div className="w-full max-w-sm"><Wheat size={32} className="text-primary mb-8 lg:hidden"/><p className="text-primary text-sm font-medium">Bem-vindo ao BakeFlow</p><h2 className="text-3xl font-semibold mt-2">Sua operação começa aqui.</h2><p className="text-muted-foreground mt-3 mb-8">Entre com sua conta para continuar.</p><form onSubmit={handleSubmit(async values => { setError(''); try { await auth.login(values.email, values.password); } catch (e) { setError(e instanceof Error ? e.message : 'Falha no login'); } })} className="space-y-5"><label className="field">E-mail<input autoComplete="username" type="email" placeholder="voce@padaria.com.br" {...register('email')}/>{errors.email && <small className="text-red-500">{errors.email.message}</small>}</label><label className="field">Senha<input autoComplete="current-password" type="password" placeholder="Sua senha" {...register('password')}/>{errors.password && <small className="text-red-500">{errors.password.message}</small>}</label>{error && <p role="alert" className="text-sm text-red-600">{error}</p>}<Button className="w-full" disabled={isSubmitting}>{isSubmitting ? 'Entrando…' : 'Entrar na plataforma'}<ArrowRight size={16}/></Button></form><p className="text-xs text-muted-foreground mt-8 leading-relaxed">Ambiente de portfólio com dados fictícios. As contas de demonstração e a configuração de acesso estão no README.</p></div></main></div>;
}
