import {useState} from 'react';
import {useQueryClient} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import {ResourcePage,Badge} from '../../components/data/resource-page';
import {EntitySelect} from '../../components/data/entity-select';
import {Dialog} from '../../components/ui/dialog';
import {Button} from '../../components/ui/button';
import {post} from '../../lib/api';
import {date,money,number} from '../../lib/utils';
export const lossLabels:Record<string,string>={EXPIRATION:'Vencimento',LEFTOVER:'Sobra',PRODUCTION_ERROR:'Erro de produção',DAMAGE:'Avaria',QUALITY:'Qualidade',OTHER:'Outro'};
interface Loss{id:string;createdAt:string;ingredient:{name:string}|null;product:{name:string}|null;lot:{id:string;lotCode:string};quantity:string;estimatedCost:string;reason:string;responsibleEmployee:{name:string}}
export function Losses(){const [open,setOpen]=useState(false);const [lotId,setLot]=useState('');const [employee,setEmployee]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const client=useQueryClient();return <><ResourcePage<Loss> title="Perdas" description="Entenda o desperdício e preserve o histórico de cada baixa." endpoint="/losses" action={{label:'Registrar perda',run:()=>{setError('');setOpen(true);}}} extra={notice&&<p role="status" className="text-sm text-emerald-600 mb-4">{notice}</p>} filters={Object.entries(lossLabels).map(([value,label])=>({value,label}))} columns={[{label:'DATA',render:r=>date(r.createdAt)},{label:'ITEM / LOTE',render:r=><div>{r.ingredient?.name??r.product?.name}<Link className="block text-xs text-primary mt-1" to={'/inventory/lots/'+r.lot.id}>{r.lot.lotCode}</Link></div>},{label:'QUANTIDADE',render:r=>number(r.quantity)},{label:'MOTIVO',render:r=><Badge tone="warning">{lossLabels[r.reason]}</Badge>},{label:'CUSTO ESTIMADO',render:r=>money(r.estimatedCost)},{label:'RESPONSÁVEL',render:r=>r.responsibleEmployee.name}]}/>{open&&<Dialog title="Registrar perda" onClose={()=>setOpen(false)}><form className="space-y-4" onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);try{await post('/losses',{...data,lotId,responsibleEmployeeId:employee});setOpen(false);setNotice('Perda registrada. O estoque foi atualizado.');void client.invalidateQueries();}catch(e){setError(e instanceof Error?e.message:'Erro');}finally{setBusy(false);}}}><EntitySelect endpoint="/inventory/lots" label="Lote" value={lotId} onChange={setLot}/><label className="field">Quantidade na unidade-base<input name="quantity" type="number" min=".000001" step=".000001" required/></label><label className="field">Motivo<select name="reason">{Object.entries(lossLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><EntitySelect endpoint="/production/people" label="Responsável" value={employee} onChange={setEmployee}/><label className="field">Observações<textarea name="notes" maxLength={1000}/></label><p className="text-xs text-muted-foreground">O saldo do lote será reduzido e a movimentação ficará registrada.</p>{error&&<p role="alert" className="text-red-600">{error}</p>}<Button disabled={busy||!lotId||!employee}>Confirmar perda</Button></form></Dialog>}</>;}
