import { useState } from 'react';
import { useQuery,useQueryClient } from '@tanstack/react-query';
import { Link,useParams } from 'react-router-dom';
import { ResourcePage,Badge } from '../../components/data/resource-page';
import { EntitySelect } from '../../components/data/entity-select';
import { Dialog } from '../../components/ui/dialog';
import { Button } from '../../components/ui/button';
import { ErrorState,Loading } from '../../components/feedback/states';
import { api,post } from '../../lib/api';
import { number,date,money } from '../../lib/utils';
import { useAuth } from '../auth/auth';
interface Lot {id:string;lotCode:string;ingredientId:string|null;ingredient:{name:string;baseUnit:string}|null;product:{name:string;unit:string}|null;expiresAt:string;manufacturedAt:string;remainingQuantity:string;initialQuantity:string;unitCost:string}
interface Balance {id:string;name:string;sku:string;unit:string;itemType:string;minimum:string;total:string;usable:string}
interface Movement {id:string;movementType:string;quantity:string;reason:string;createdAt:string;ingredient:{name:string}|null;product:{name:string}|null;lot:{lotCode:string};creator:{name:string}}
export function Inventory() {
 const [tab,setTab]=useState('balances');const [entry,setEntry]=useState(false);const [exit,setExit]=useState<Lot|null>(null);const [notice,setNotice]=useState('');const client=useQueryClient();const {user}=useAuth();const write=['ADMIN','MANAGER','STOCK'].includes(user?.role??'');
 const tabs=<div className="flex gap-2 mb-6">{[['balances','Saldos'],['lots','Lotes e validade'],['movements','Movimentações']].map(([key,label])=><Button key={key} variant={tab===key?'default':'outline'} onClick={()=>setTab(key)}>{label}</Button>)}</div>;
 const done=()=>{setEntry(false);setExit(null);setNotice('Ajuste registrado e estoque atualizado.');void client.invalidateQueries();};
 const common={title:'Estoque',description:'Saldos auditáveis, validade e rastreabilidade em uma visão.',extra:<>{tabs}{notice&&<p role="status" className="text-emerald-600 mb-4 text-sm">{notice}</p>}</>,action:write?{label:'Entrada por ajuste',run:()=>setEntry(true)}:undefined};
 return <>{tab==='balances'?<ResourcePage<Balance> {...common} endpoint="/inventory" filters={[{value:'LOW',label:'Abaixo do mínimo'}]} columns={[{label:'ITEM',render:r=><div className="font-medium">{r.name}<p className="text-xs text-muted-foreground mt-1">{r.sku} · {r.itemType==='INGREDIENT'?'Insumo':'Produto'}</p></div>},{label:'SALDO FÍSICO',render:r=>number(r.total)+' '+r.unit},{label:'UTILIZÁVEL',render:r=>number(r.usable)+' '+r.unit},{label:'MÍNIMO',render:r=>number(r.minimum)+' '+r.unit},{label:'SITUAÇÃO',render:r=><Badge tone={Number(r.usable)<Number(r.minimum)?'warning':'success'}>{Number(r.usable)<Number(r.minimum)?'Estoque baixo':'Regular'}</Badge>}]}/>:tab==='lots'?<ResourcePage<Lot> {...common} endpoint="/inventory/lots" filters={[{value:'AVAILABLE',label:'Utilizáveis'},{value:'EXPIRING',label:'Vencem em 7 dias'},{value:'EXPIRED',label:'Vencidos'}]} columns={[{label:'LOTE / ITEM',render:r=><div><Link className="font-medium text-primary" to={'/inventory/lots/'+r.id}>{r.lotCode}</Link><p className="text-xs text-muted-foreground mt-1">{r.ingredient?.name??r.product?.name}</p></div>},{label:'VALIDADE',render:r=>date(r.expiresAt)},{label:'SALDO',render:r=>number(r.remainingQuantity)+' '+(r.ingredient?.baseUnit??r.product?.unit)},{label:'CUSTO UNITÁRIO',render:r=>money(r.unitCost)},{label:'',render:r=>write&&Number(r.remainingQuantity)>0?<Button variant="outline" size="sm" onClick={()=>setExit(r)}>Ajustar saída</Button>:null}]}/>:<ResourcePage<Movement> {...common} endpoint="/inventory/movements" columns={[{label:'DATA',render:r=>date(r.createdAt)},{label:'MOVIMENTO',render:r=><Badge>{r.movementType}</Badge>},{label:'ITEM / LOTE',render:r=><div>{r.ingredient?.name??r.product?.name}<p className="text-xs text-muted-foreground">{r.lot.lotCode}</p></div>},{label:'QUANTIDADE',render:r=>number(r.quantity)},{label:'MOTIVO',render:r=>r.reason},{label:'USUÁRIO',render:r=>r.creator.name}]}/ >}{entry&&<EntryForm onClose={()=>setEntry(false)} onDone={done}/ >}{exit&&<ExitForm lot={exit} onClose={()=>setExit(null)} onDone={done}/>}</>;
}
function EntryForm({onClose,onDone}:{onClose:()=>void;onDone:()=>void}) {
 const [type,setType]=useState('INGREDIENT');const [itemId,setItem]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 return <Dialog title="Entrada por ajuste" onClose={onClose}><form className="space-y-4" onSubmit={async e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);try{await post('/inventory/adjustments/entry',{...values,itemType:type,itemId});onDone();}catch(e){setError(e instanceof Error?e.message:'Erro ao registrar');}finally{setBusy(false);}}}><label className="field">Tipo<select value={type} onChange={e=>{setType(e.target.value);setItem('');}}><option value="INGREDIENT">Insumo</option><option value="PRODUCT">Produto acabado</option></select></label><EntitySelect endpoint={type==='INGREDIENT'?'/ingredients?status=ACTIVE':'/products?status=ACTIVE'} label="Item" value={itemId} onChange={setItem}/><div className="grid sm:grid-cols-2 gap-4">{[['lotCode','Código do lote','text'],['quantity','Quantidade na unidade-base','number'],['unitCost','Custo por unidade-base (R$)','number'],['manufacturedAt','Fabricação','date'],['expiresAt','Validade','date']].map(([name,label,type])=><label className="field" key={name}>{label}<input name={name} type={type} required min={name==='quantity'?'.000001':'0'} step=".000001"/></label>)}</div><label className="field">Justificativa<textarea name="reason" required minLength={5}/></label>{error&&<p role="alert" className="text-red-600 text-sm">{error}</p>}<Button disabled={busy||!itemId}>Registrar entrada</Button></form></Dialog>;
}
function ExitForm({lot,onClose,onDone}:{lot:Lot;onClose:()=>void;onDone:()=>void}) {const [error,setError]=useState('');const [busy,setBusy]=useState(false);return <Dialog title={'Ajuste de saída · '+lot.lotCode} onClose={onClose}><form className="space-y-4" onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);try{await post('/inventory/adjustments/exit',{...data,lotId:lot.id});onDone();}catch(e){setError(e instanceof Error?e.message:'Erro');}finally{setBusy(false);}}}><p className="text-sm text-muted-foreground">Saldo: {number(lot.remainingQuantity)}. Esta ação gera um movimento auditável.</p><label className="field">Quantidade<input name="quantity" type="number" min=".000001" max={lot.remainingQuantity} step=".000001" required/></label><label className="field">Justificativa<textarea name="reason" minLength={5} required/></label>{error&&<p role="alert" className="text-red-600">{error}</p>}<Button disabled={busy}>Confirmar saída</Button></form></Dialog>;}
export function LotDetail() {
 const {id}=useParams();const q=useQuery({queryKey:['lot',id],queryFn:()=>api<Lot&{productionOrder:null|{completedAt:string;totalCost:string;responsibleEmployee:{name:string};recipeVersion:{version:number;recipe:{name:string}};consumptions:{id:string;quantity:string;unitCost:string;ingredient:{name:string};inventoryLot:{id:string;lotCode:string}}[]}} >('/inventory/lots/'+id)});
 if(q.isPending)return <Loading/>;if(q.isError)return <ErrorState error={q.error}/>;const lot=q.data;const production=lot.productionOrder;
 return <><Link to="/inventory" className="text-sm text-muted-foreground">← Estoque</Link><h1 className="page-title mt-5">{lot.lotCode}</h1><p className="page-description">{lot.ingredient?.name??lot.product?.name}</p><div className="grid sm:grid-cols-3 gap-5 mt-7"><section className="card"><p className="text-muted-foreground text-sm">Saldo / inicial</p><p className="text-2xl mt-2">{number(lot.remainingQuantity)} / {number(lot.initialQuantity)}</p></section><section className="card"><p className="text-muted-foreground text-sm">Validade</p><p className="text-2xl mt-2">{date(lot.expiresAt)}</p></section><section className="card"><p className="text-muted-foreground text-sm">Custo por unidade</p><p className="text-2xl mt-2">{money(lot.unitCost)}</p></section></div>{production&&<section className="card mt-6"><h2 className="font-semibold">Rastreabilidade da produção</h2><p className="text-sm text-muted-foreground mt-3">{date(production.completedAt)} · {production.responsibleEmployee.name} · {production.recipeVersion.recipe.name} v{production.recipeVersion.version}</p><div className="overflow-x-auto mt-5"><table><thead><tr><th>INSUMO</th><th>LOTE DE ORIGEM</th><th>CONSUMO</th><th>CUSTO UNITÁRIO HISTÓRICO</th></tr></thead><tbody>{production.consumptions.map(c=><tr key={c.id}><td>{c.ingredient.name}</td><td><Link className="text-primary" to={'/inventory/lots/'+c.inventoryLot.id}>{c.inventoryLot.lotCode}</Link></td><td>{number(c.quantity)}</td><td>{money(c.unitCost)}</td></tr>)}</tbody></table></div><p className="mt-5 font-semibold">Custo total: {money(production.totalCost)}</p></section>}</>;
}
