import {test,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {db} from '../src/shared/database.js';
import {catalogService} from '../src/modules/catalog/service.js';
import {inventoryService} from '../src/modules/inventory/service.js';
import {productionService} from '../src/modules/production/service.js';
test('production rolls back late failure, uses fixed recipe/cost and creates traceable output atomically',async()=>{
 const key=randomUUID();const user=await db.user.findUniqueOrThrow({where:{email:'admin@bakeflow.demo'}});
 const ic=await db.ingredientCategory.create({data:{name:key}});const pc=await db.productCategory.create({data:{name:key}});
 const ingredient=await db.ingredient.create({data:{name:key,sku:key,categoryId:ic.id,baseUnit:'KG'}});const product=await db.product.create({data:{name:key,sku:key,categoryId:pc.id,unit:'UNIT',salePrice:10}});
 const employee=await db.employee.create({data:{name:'Padeiro teste',cpf:key,birthDate:new Date('1990-01-01'),hireDate:new Date('2020-01-01'),jobTitle:'Padeiro',salary:3000,workSchedule:'Manhã'}});
 const recipe=await catalogService.createRecipe({name:key,productId:product.id,yieldQuantity:1,items:[{ingredientId:ingredient.id,quantity:1,unit:'KG'}]});
 const entry=(suffix:string,quantity:number,unitCost:number,expiresAt:string)=>inventoryService.entry({itemType:'INGREDIENT',itemId:ingredient.id,quantity,unitCost,lotCode:key+suffix,manufacturedAt:'2020-01-01',expiresAt,reason:'Estoque para teste'},user.id);
 const first=await entry('a',20,5,'2090-01-01');const second=await entry('b',50,7,'2091-01-01');await entry('expired',100,1,'2020-02-01');
 const create=()=>productionService.create({productId:product.id,recipeVersionId:recipe.versions[0].id,plannedQuantity:25,responsibleEmployeeId:employee.id});
 const order=await create();
 await catalogService.version(recipe.id,{yieldQuantity:1,items:[{ingredientId:ingredient.id,quantity:2,unit:'KG'}]});
 await expect(productionService.complete(order.id,{producedQuantity:25,lotCode:first.lotCode,expiresAt:'2090-01-01'},user.id)).rejects.toThrow();
 expect((await db.inventoryLot.findUniqueOrThrow({where:{id:first.id}})).remainingQuantity.toString()).toBe('20');
 expect(await db.productionConsumption.count({where:{productionOrderId:order.id}})).toBe(0);
 expect(await db.inventoryMovement.count({where:{referenceId:order.id}})).toBe(0);
 const done=await productionService.complete(order.id,{producedQuantity:25,lotCode:key+'output',expiresAt:'2090-01-01'},user.id);
 expect(done.totalCost.toString()).toBe('135');expect(done.recipeVersionId).toBe(recipe.versions[0].id);
 expect(done.outputLot.remainingQuantity.toString()).toBe('25');
 expect((await db.inventoryLot.findUniqueOrThrow({where:{id:second.id}})).remainingQuantity.toString()).toBe('45');
 expect(await db.productionConsumption.count({where:{productionOrderId:order.id}})).toBe(2);
 await entry('newPrice',1,99,'2092-01-01');
 expect((await db.productionOrder.findUniqueOrThrow({where:{id:order.id}})).totalCost.toString()).toBe('135');
 const missing=await create();await expect(productionService.complete(missing.id,{producedQuantity:1000,lotCode:key+'missing',expiresAt:'2090-01-01'},user.id)).rejects.toMatchObject({code:'INSUFFICIENT_STOCK'});
 expect((await db.productionOrder.findUniqueOrThrow({where:{id:missing.id}})).status).toBe('PLANNED');
 const [one,two]=await Promise.all([create(),create()]);
 const outcomes=await Promise.allSettled([one,two].map((o,i)=>productionService.complete(o.id,{producedQuantity:40,lotCode:key+'concurrent'+i,expiresAt:'2090-01-01'},user.id)));
 expect(outcomes.filter(o=>o.status==='fulfilled')).toHaveLength(1);
 expect(outcomes.filter(o=>o.status==='rejected')).toHaveLength(1);
});
