import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import {ResourcePage,Badge} from '../../components/data/resource-page';
import {EntitySelect} from '../../components/data/entity-select';
import {Dialog} from '../../components/ui/dialog';
import {Button} from '../../components/ui/button';
import {api,post} from '../../lib/api';
import {number,money,date} from '../../lib/utils';
const labels:Record<string,string>={PLANNED:'Planejada',IN_PROGRESS:'Em produção',COMPLETED:'Concluída',CANCELLED:'Cancelada'};
interface Order{id:string;product:{name:string};plannedQuantity:string;producedQuantity:string;status:string;totalCost:string;createdAt:string;responsibleEmployee:{name:string};recipeVersion:{version:number};outputLot:{id:string;lotCode:string}|null}
interface Plan{id:string;productionDate:string;status:string;items:{id:string;plannedQuantity:string;product:{name:string}}[]}
export function Production(){const [tab,setTab]=useState('orders');const [create,setCreate]=useState(false);const [plan,setPlan]=useState(false);const [complete,setComplete]=useState<Order|null>(null);const [error,setError]=useState('');const client=useQueryClient();const done=()=>{setCreate(false);setPlan(false);setComplete(null);void client.invalidateQueries();};async function status(id:string,status:string){try{await api('/production/'+id+'/status',{method:'PATCH',body:JSON.stringify({status})});done();}catch(e){setError(e instanceof Error?e.message:'Erro');}}
 const extra=<><div className="flex gap-2 mb-5"><Button variant={tab==='orders'?'default':'outline'} onClick={()=>setTab('orders')}>Ordens de produção</Button><Button variant={tab==='plans'?'default':'outline'} onClick={()=>setTab('plans')}>Planejamento</Button></div>{error&&<p role="alert" className="text-red-600 mb-4">{error}</p>}</>;
 return <>{tab==='orders'?<ResourcePage<Order> title="Produção" description="Cada fornada conectada à receita, aos lotes e ao custo real." endpoint="/production" extra={extra} action={{label:'Nova produção',run:()=>setCreate(true)}} filters={Object.entries(labels).map(([value,label])=>({value,label}))} columns={[{label:'PRODUTO',render:r=><div className="font-medium">{r.product.name}<p className="text-xs text-muted-foreground">Receita v{r.recipeVersion.version} · {date(r.createdAt)}</p></div>},{label:'PLANEJADO / PRODUZIDO',render:r=>number(r.plannedQuantity)+' / '+number(r.producedQuantity)},{label:'RESPONSÁVEL',render:r=>r.responsibleEmployee.name},{label:'CUSTO REAL',render:r=>money(r.totalCost)},{label:'STATUS',render:r=><Badge tone={r.status==='COMPLETED'?'success':r.status==='IN_PROGRESS'?'warning':'neutral'}>{labels[r.status]}</Badge>},{label:'AÇÕES',render:r=><div className="flex gap-2">{r.status==='PLANNED'&&<Button size="sm" variant="outline" onClick={()=>void status(r.id,'IN_PROGRESS')}>Iniciar</Button>}{['PLANNED','IN_PROGRESS'].includes(r.status)&&<><Button size="sm" onClick={()=>{setError('');setComplete(r);}}>Concluir</Button><Button size="sm" variant="ghost" onClick={()=>void status(r.id,'CANCELLED')}>Cancelar</Button></>}{r.outputLot&&<Link className="text-primary" to={'/inventory/lots/'+r.outputLot.id}>{r.outputLot.lotCode}</Link>}</div>}]}/>:<ResourcePage<Plan> title="Planejamento" description="Antecipe a necessidade de insumos e identifique faltas antes da produção." endpoint="/production/plans" extra={extra} action={{label:'Novo planejamento',run:()=>setPlan(true)}} columns={[{label:'DATA',render:r=>date(r.productionDate)},{label:'PRODUTOS',render:r=><div>{r.items.map(i=><p key={i.id}>{i.product.name} · {number(i.plannedQuantity)}</p>)}</div>},{label:'STATUS',render:r=><Badge>{r.status}</Badge>}]}/ >}{create&&<OrderForm onClose={()=>setCreate(false)} onDone={done}/ >}{plan&&<PlanForm onClose={()=>setPlan(false)} onDone={done}/ >}{complete&&<CompleteForm order={complete} onClose={()=>setComplete(null)} onDone={done}/>}</>;
}
function OrderForm({onClose,onDone}:{onClose:()=>void;onDone:()=>void}){const [productId,setProduct]=useState('');const [employee,setEmployee]=useState('');const [version,setVersion]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const q=useQuery({queryKey:['product-recipes',productId],enabled:!!productId,queryFn:()=>api<{recipes:{id:string;name:string;active:boolean;versions:{id:string;version:number}[]}[]}>('/products/'+productId)});return <Dialog title="Nova ordem de produção" onClose={onClose}><form className="space-y-5" onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);try{await post('/production',{...data,productId,recipeVersionId:version,responsibleEmployeeId:employee});onDone();}catch(e){setError(e instanceof Error?e.message:'Erro');}finally{setBusy(false);}}}><EntitySelect endpoint="/products?status=ACTIVE" label="Produto" value={productId} onChange={id=>{setProduct(id);setVersion('');}}/><label className="field">Versão da receita<select required value={version} onChange={e=>setVersion(e.target.value)}><option value="">Selecione a ficha técnica</option>{q.data?.recipes.filter(r=>r.active).flatMap(r=>r.versions.map(v=><option value={v.id} key={v.id}>{r.name} · v{v.version}</option>))}</select></label>{q.isError&&<p role="alert">{q.error.message}</p>}<label className="field">Quantidade planejada<input name="plannedQuantity" type="number" min=".000001" step=".000001" required/></label><EntitySelect endpoint="/production/people" label="Responsável" value={employee} onChange={setEmployee}/>{error&&<p role="alert" className="text-red-600">{error}</p>}<Button disabled={busy||!version||!employee}>Criar produção</Button></form></Dialog>;}
function CompleteForm({order,onClose,onDone}:{order:Order;onClose:()=>void;onDone:()=>void}){const [error,setError]=useState('');const [busy,setBusy]=useState(false);return <Dialog title={'Concluir · '+order.product.name} onClose={onClose}><form className="space-y-4" onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);try{await post('/production/'+order.id+'/complete',data);onDone();}catch(e){setError(e instanceof Error?e.message:'Erro');}finally{setBusy(false);}}}><p className="text-sm text-muted-foreground">A confirmação consome insumos por FEFO e gera o lote acabado. Se faltar qualquer ingrediente, nenhuma baixa será realizada.</p><label className="field">Quantidade produzida<input name="producedQuantity" type="number" min=".000001" step=".000001" defaultValue={order.plannedQuantity} required/></label><label className="field">Código do lote acabado<input name="lotCode" required minLength={2}/></label><label className="field">Validade<input name="expiresAt" type="date" required/></label>{error&&<p role="alert" className="text-red-600">{error}</p>}<Button disabled={busy}>{busy?'Registrando…':'Confirmar produção'}</Button></form></Dialog>;}
function PlanForm({onClose,onDone}:{onClose:()=>void;onDone:()=>void}){const [productionDate,setDate]=useState(new Date().toISOString().slice(0,10));const [items,setItems]=useState([{productId:'',plannedQuantity:1}]);const [needs,setNeeds]=useState<{ingredientId:string;name:string;unit:string;required:string;available:string;missing:string}[]|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);async function run(save:boolean){setBusy(true);setError('');try{const body={productionDate,items};if(save){await post('/production/plans',body);onDone();}else setNeeds(await post('/production/requirements',body));}catch(e){setError(e instanceof Error?e.message:'Erro');}finally{setBusy(false);}}return <Dialog title="Planejar produção" onClose={onClose}><div className="space-y-4"><label className="field">Data de produção<input type="date" value={productionDate} onChange={e=>{setDate(e.target.value);setNeeds(null);}}/></label>{items.map((item,n)=><div className="border p-4 rounded-lg space-y-3" key={n}><EntitySelect endpoint="/products?status=ACTIVE" label={'Produto '+(n+1)} value={item.productId} onChange={id=>{setItems(items.map((i,index)=>index===n?{...i,productId:id}:i));setNeeds(null);}}/><label className="field">Quantidade<input type="number" min=".000001" value={item.plannedQuantity} onChange={e=>{setItems(items.map((i,index)=>index===n?{...i,plannedQuantity:Number(e.target.value)}:i));setNeeds(null);}}/></label></div>)}<Button variant="outline" onClick={()=>{setItems([...items,{productId:'',plannedQuantity:1}]);setNeeds(null);}}>Adicionar produto</Button>{error&&<p role="alert" className="text-red-600">{error}</p>}{needs&&<div className="overflow-x-auto"><table><thead><tr><th>INSUMO</th><th>NECESSÁRIO</th><th>UTILIZÁVEL</th><th>FALTA</th></tr></thead><tbody>{needs.map(n=><tr key={n.ingredientId}><td>{n.name}</td><td>{number(n.required)} {n.unit}</td><td>{number(n.available)}</td><td className={Number(n.missing)>0?'text-red-600 font-semibold':'text-emerald-600'}>{number(n.missing)}</td></tr>)}</tbody></table></div>}<div className="flex gap-2"><Button variant="outline" disabled={busy||items.some(i=>!i.productId)} onClick={()=>void run(false)}>Calcular necessidade</Button><Button disabled={busy||items.some(i=>!i.productId)} onClick={()=>void run(true)}>Salvar planejamento</Button></div></div></Dialog>;}
